import type { Event } from '@/types';

// Helper to get dates relative to today
const daysFromNow = (days: number) => new Date(Date.now() + days * 24 * 60 * 60 * 1000).toISOString();

export const dummyEvents: Event[] = [
  // Upcoming Events
  {
    id: 101,
    created_at: daysFromNow(-10),
    title: 'Future Soundscapes Festival',
    description: 'A 3-day festival celebrating the future of electronic music.',
    date: daysFromNow(30),
    location: 'Lagos, Nigeria',
    image_url: 'https://images.unsplash.com/photo-1574169208507-84376144848b?q=80&w=800&h=600&auto=format&fit=crop',
    price: 15000,
    currency: 'NGN',
    featured: true,
    sold_out: false,
  },
  {
    id: 102,
    created_at: daysFromNow(-15),
    title: 'London Tech Innovators Summit',
    description: 'The premier conference for tech leaders and innovators.',
    date: daysFromNow(45),
    location: 'London, UK',
    image_url: 'https://images.unsplash.com/photo-1496065187959-7f07b8353c55?q=80&w=800&h=600&auto=format&fit=crop',
    price: 250,
    currency: 'GBP',
    featured: true,
    sold_out: false,
  },
  {
    id: 103,
    created_at: daysFromNow(-5),
    title: 'Local Artisans Market',
    description: 'Discover and support local creators and artisans.',
    date: daysFromNow(14),
    location: 'Abuja, Nigeria',
    image_url: 'https://images.unsplash.com/photo-1524233803964-32f4614f57a3?q=80&w=800&h=600&auto=format&fit=crop',
    price: 0,
    currency: 'NGN',
    featured: false,
    sold_out: false,
  },
  // Past Events
  {
    id: 201,
    created_at: daysFromNow(-90),
    title: 'Vintage Rock Revival Tour',
    description: 'A throwback concert featuring classic rock anthems.',
    date: daysFromNow(-30),
    location: 'Manchester, UK',
    image_url: 'https://images.unsplash.com/photo-1547929424-c1d76473de44?q=80&w=800&h=600&auto=format&fit=crop',
    price: 75,
    currency: 'GBP',
    featured: false,
    sold_out: true,
  },
  {
    id: 202,
    created_at: daysFromNow(-80),
    title: 'Afro-Fusion Fest 2023',
    description: 'The biggest celebration of Afro-fusion music and culture.',
    date: daysFromNow(-60),
    location: 'Lagos, Nigeria',
    image_url: 'https://images.unsplash.com/photo-1619074404058-5296b489d34a?q=80&w=800&h=600&auto=format&fit=crop',
    price: 8000,
    currency: 'NGN',
    featured: false,
    sold_out: true,
  },
  {
    id: 203,
    created_at: daysFromNow(-70),
    title: 'The Comedy Showcase',
    description: 'A night of laughter with the nation\'s top comedians.',
    date: daysFromNow(-45),
    location: 'London, UK',
    image_url: 'https://images.unsplash.com/photo-1598809439837-586558428a2a?q=80&w=800&h=600&auto=format&fit=crop',
    price: 40,
    currency: 'GBP',
    featured: false,
    sold_out: false,
  },
  {
    id: 204,
    created_at: daysFromNow(-60),
    title: 'Annual Charity Gala',
    description: 'An elegant evening of dining and fundraising for a good cause.',
    date: daysFromNow(-20),
    location: 'Abuja, Nigeria',
    image_url: 'https://images.unsplash.com/photo-1529224463424-951859b58468?q=80&w=800&h=600&auto=format&fit=crop',
    price: 50000,
    currency: 'NGN',
    featured: false,
    sold_out: true,
  },
]; 